version: '3'
services:
  server:
    image: redash/redash:latest
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5001:5000"
    environment:
      REDASH_COOKIE_SECRET: redash-selfhosted
      REDASH_SECRET_KEY: redash-selfhosted
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://postgres:postgres@postgres/postgres
      REDASH_MAIL_SERVER: email
      REDASH_MAIL_PORT: 1025
      REDASH_MAIL_USE_TLS: "false"
      REDASH_MAIL_DEFAULT_SENDER: redash@example.com
    restart: always
    
  worker:
    image: redash/redash:latest
    command: worker
    depends_on:
      - server
    environment:
      REDASH_COOKIE_SECRET: redash-selfhosted
      REDASH_SECRET_KEY: redash-selfhosted
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://postgres:postgres@postgres/postgres
      REDASH_MAIL_SERVER: email
      REDASH_MAIL_PORT: 1025
      REDASH_MAIL_USE_TLS: "false"
      REDASH_MAIL_DEFAULT_SENDER: redash@example.com
    restart: always
    
  scheduler:
    image: redash/redash:latest
    command: scheduler
    depends_on:
      - server
    environment:
      REDASH_COOKIE_SECRET: redash-selfhosted
      REDASH_SECRET_KEY: redash-selfhosted
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://postgres:postgres@postgres/postgres
      REDASH_MAIL_SERVER: email
      REDASH_MAIL_PORT: 1025
      REDASH_MAIL_USE_TLS: "false"
      REDASH_MAIL_DEFAULT_SENDER: redash@example.com
    restart: always
    
  redis:
    image: redis:7.0-alpine
    restart: always
    volumes:
      - ./data/redis:/data
      
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    
  email:
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"
    restart: always